# Generated by Django 4.1.4 on 2022-12-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postare',
            name='titlu_nav',
            field=models.CharField(default='My Travel Blog', max_length=500),
        ),
    ]
