# Generated by Django 4.1.4 on 2023-01-03 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travelblog', '0002_postare_titlu_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='postare',
            name='data_postare',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postare',
            name='titlu_nav',
            field=models.CharField(max_length=500),
        ),
    ]
