# Generated by Django 4.1.4 on 2023-01-03 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelblog', '0003_postare_data_postare_alter_postare_titlu_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='postare',
            name='likes',
            field=models.ManyToManyField(related_name='postare_blog', to=settings.AUTH_USER_MODEL),
        ),
    ]
