# Generated by Django 4.1.4 on 2023-01-05 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelblog', '0006_tipuri_postare_tipuri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postare',
            name='likes',
            field=models.ManyToManyField(related_name='postare_blog', to=settings.AUTH_USER_MODEL),
        ),
    ]
